CZBK.ItcastOA.WebApp/Controllers/UserInfoController.cs
using CZBK.ItcastOA.Model;
using CZBK.ItcastOA.Model.EnumType;
using CZBK.ItcastOA.Model.Search;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CZBK.ItcastOA.WebApp.Controllers
{
    public class UserInfoController :BaseController //Controller
    {
        //
        // GET: /UserInfo/
        IBLL.IUserInfoService UserInfoService{get;set;}
        IBLL.IRoleInfoService RoleInfoService { get; set; }
        IBLL.IActionInfoService ActionInfoService { get; set; }
        IBLL.IR_UserInfo_ActionInfoService R_UserInfo_ActionInfoService { get; set; }
        public ActionResult Index()
        {
            return View();
        }

        #region 获取用户列表数据
        public ActionResult GetUserInfoList()
        {
            int pageIndex = Request["page"] != null ? int.Parse(Request["page"]) : 1;
            int pageSize = Request["rows"] != null ? int.Parse(Request["rows"]) : 5;
            //接收搜索条件
            string userName = Request["name"];
            string userRemark = Request["remark"];
             int totalCount=0;
            //构建搜索条件.
            UserInfoSearch userInfoSearch = new UserInfoSearch() { 
              UserName=userName,
              UserRemark=userRemark,
              PageIndex=pageIndex,
              PageSize=pageSize,
              TotalCount=totalCount
            };
            short delFlag = (short)DeleteEnumType.Normarl;
            //根据构建好的搜索条件完成搜索
            var userInfoList = UserInfoService.LoadSearchEntities(userInfoSearch, delFlag);
           
           
            //获取分页数据。
            //var userInfoList= UserInfoService.LoadPageEntities<int>(pageIndex, pageSize, out totalCount, c => c.DelFlag == delFlag, c => c.ID,true);

            var temp = from u in userInfoList
                       select new {
                           ID=u.ID,
                       UName=u.UName,
                       UPwd=u.UPwd,
                       Remark=u.Remark,
                       SubTime=u.SubTime
                       };

            return Json(new { rows = temp, total = userInfoSearch.TotalCount }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 删除用户数据
        public ActionResult DeleteUserInfo()
        {
            string strId=Request["strId"];
            string[]strIds=strId.Split(',');
            List<int> list = new List<int>();
            foreach (string id in strIds)
            {
                list.Add(Convert.ToInt32(id));
            }
            //将list集合存储的的要删除的记录的编号传递到业务层.
            if (UserInfoService.DeleteEntities(list))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }
        #endregion

        #region 添加用户数据
        public ActionResult AddUserInfo(UserInfo userInfo)
        {
            userInfo.DelFlag = 0;
            userInfo.ModifiedOn = DateTime.Now;
            userInfo.SubTime = DateTime.Now;
            UserInfoService.AddEntity(userInfo);
            return Content("ok");
        }
        #endregion
        #region 展示要修改的数据
        public ActionResult ShowEditInfo()
        {
            int id = int.Parse(Request["id"]);
           var userInfo= UserInfoService.LoadEntities(u=>u.ID==id).FirstOrDefault();
           return Json(userInfo, JsonRequestBehavior.AllowGet);
        }

        #endregion
        #region 完成用户数据的更新
         public ActionResult EditUserInfo(UserInfo userInfo)
        {
        
            userInfo.ModifiedOn = DateTime.Now;
            if (UserInfoService.EditEntity(userInfo))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }
        #endregion

        #region 展示用户已经有的角色
         public ActionResult ShowUserRoleInfo()
         {
             int id = int.Parse(Request["id"]);
            var userInfo= UserInfoService.LoadEntities(u=>u.ID==id).FirstOrDefault();
            ViewBag.UserInfo = userInfo;
            //查询所有的角色.
              short delFlag = (short)DeleteEnumType.Normarl;
           var allRoleList= RoleInfoService.LoadEntities(r=>r.DelFlag==delFlag).ToList();
             //查询一下要分配角色的用户以前具有了哪些角色编号。
           var allUserRoleIdList = (from r in userInfo.RoleInfo
                                    select r.ID).ToList();
           ViewBag.AllRoleList = allRoleList;
           ViewBag.AllUserRoleIdList = allUserRoleIdList;
           return View();
         }

        #endregion

        #region 完成用户角色的分配
         public ActionResult SetUserRoleInfo()
         {
             int userId = int.Parse(Request["userId"]);
             string[]allKeys=Request.Form.AllKeys;//获取所有表单元素name属性值。
             List<int> roleIdList = new List<int>();
             foreach (string key in allKeys)
             {
                 if (key.StartsWith("cba_"))
                 {
                     string k = key.Replace("cba_","");
                     roleIdList.Add(Convert.ToInt32(k));
                 }
             }
             if (UserInfoService.SetUserRoleInfo(userId, roleIdList))//设置用户的角色
             {
                 return Content("ok");
             }
             else
             {
                 return Content("no");
             }
         }

        #endregion
        #region 展示用户权限
         public ActionResult ShowUserAction()
         {
             int userId = int.Parse(Request["userId"]);
            var userInfo=UserInfoService.LoadEntities(u=>u.ID==userId).FirstOrDefault();
            ViewBag.UserInfo = userInfo;
             //获取所有的权限。
             short delFlag = (short)DeleteEnumType.Normarl;
            var allActionList= ActionInfoService.LoadEntities(a => a.DelFlag == delFlag).ToList();
             //获取要分配的用户已经有的权限。
            var allActionIdList = (from a in userInfo.R_UserInfo_ActionInfo
                                   select a).ToList();
            ViewBag.AllActionList = allActionList;
            ViewBag.AllActionIdList = allActionIdList;
            return View();
         }
        #endregion

        #region 完成用户权限的分配
         public ActionResult SetUserAction()
         {
             int actionId = int.Parse(Request["actionId"]);
             int userId = int.Parse(Request["userId"]);
             bool isPass = Request["isPass"] == "true" ? true : false;
             if (UserInfoService.SetUserActionInfo(actionId, userId, isPass))
             {
                 return Content("ok");
             }
             else
             {
                 return Content("no");
             }
         }
        #endregion

        #region 完成权限删除
         public ActionResult ClearUserAction()
         {
             int actionId = int.Parse(Request["actionId"]);
             int userId = int.Parse(Request["userId"]);
           var r_userInfo_actionInfo=R_UserInfo_ActionInfoService.LoadEntities(r=>r.ActionInfoID==actionId&&r.UserInfoID==userId).FirstOrDefault();
           if (r_userInfo_actionInfo != null)
           {
               if (R_UserInfo_ActionInfoService.DeleteEntity(r_userInfo_actionInfo))
               {
                   return Content("ok:删除成功!!");
               }
               else
               {
                   return Content("ok:删除失败!!");
               }
           }
           else
           {
               return Content("no:数据不存在!!");
           }

         }
        #endregion

    }
}

CZBK.ItcastOA.WebApp/Views/UserInfo/ShowUserAction.cshtml
@{
    Layout = null;
}
@using CZBK.ItcastOA.Model
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>为用户分配权限</title>
    <link href="~/Content/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/themes/icon.css" rel="stylesheet" />
    <link href="~/Content/tableStyle.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
</head>
<body>
    <div>
        为用户 @{
            UserInfo userInfo = ViewBag.UserInfo;
            <span style="font-size:14px;color:red;font-weight:bold"> @userInfo.UName</span>
        }分配权限
        <br />
        <table>
            <tr><th>编号</th><th>权限名称</th><th>Url</th><th>HttpMethod</th><th>操作</th></tr>
            @{
                List<ActionInfo> allActionList = ViewBag.AllActionList;
                List<R_UserInfo_ActionInfo>allActionId= ViewBag.AllActionIdList;
                foreach(ActionInfo actionInfo in allActionList){
                    var actionName = "cba_" + actionInfo.ID;
                    var noactionName = "nocba_"+actionInfo.ID;
                   <tr>
                       <td>@actionInfo.ID</td>
                       <td>@actionInfo.ActionInfoName</td>
                       <td>@actionInfo.Url</td>
                       <td>@actionInfo.HttpMethod</td>
                       <td>
                           @{
                    var isExt = (from a in allActionId
                                where a.ActionInfoID== actionInfo.ID
                                select a).FirstOrDefault();
                    if (isExt != null)
                    {
                        if (isExt.IsPass)
                        {
                           <label for="@actionName">允许</label>
                               <input type="radio" checked="checked" value="true" class="selectActions" ids="@actionInfo.ID" id="@actionName" name="@actionName"/>
                                <label for="@noactionName">禁止</label>
                               <input type="radio" value="false" class="selectActions" ids="@actionInfo.ID" id="@noactionName" name="@actionName"/>
                             
                        }
                        else
                        {
                            
                             <label for="@actionName">允许</label>
                               <input type="radio"  value="true" class="selectActions" ids="@actionInfo.ID" id="@actionName" name="@actionName"/>
                                <label for="@noactionName">禁止</label>
                               <input type="radio" value="false" class="selectActions" ids="@actionInfo.ID" checked="checked" id="@noactionName" name="@actionName"/>
                        }

                    }
                    else
                    {
                          <label for="@actionName">允许</label>
                               <input type="radio"  value="true" class="selectActions" ids="@actionInfo.ID" id="@actionName" name="@actionName"/>
                                <label for="@noactionName">禁止</label>
                               <input type="radio" value="false" class="selectActions" ids="@actionInfo.ID" id="@noactionName" name="@actionName"/>
                        
                    }
                           <input type="button" value="清除" class="btnClear" ids="@actionInfo.ID" />    
                               
                               }

                       </td>
                   </tr>
                }
            }
        </table>
    </div>
</body>
</html>
<script type="text/javascript">
    $(function () {
        bindRadioClickEvent();
        bindClearBtnClickEvent();
    });
    //单击“单选按钮”完成权限的分配
    function bindRadioClickEvent() {
        $(".selectActions").click(function () {
            var actionId = $(this).attr("ids");//获取权限编号
            var isPass=$(this).val();
            $.post("/UserInfo/SetUserAction", { "actionId": actionId, "userId": '@userInfo.ID', "isPass": isPass }, function (data) {
                if (data == "ok") {
                    $.messager.show({
                        title: '提示',
                        msg: '权限分配成功',
                        showType: 'show'
                    });

                } else {
                    $.messager.show({
                        title: '提示',
                        msg: '权限分配失败',
                        showType: 'show'
                    });
                }
            });
        });
    }
    //清除权限
    function bindClearBtnClickEvent() {
        $(".btnClear").click(function () {
            var actionId = $(this).attr("ids");//获取权限编号
            var $control=$(this)
            $.post("/UserInfo/ClearUserAction", { "actionId": actionId, "userId": '@userInfo.ID' }, function (data) {
                var serverData = data.split(':');
                if (serverData[0] == "ok") {
                    $control.parent().find(".selectActions").removeAttr("checked");
                    showMsg(serverData[1]);
                } else {
                    showMsg(serverData[1]);
                }
            });
        });
    }
    function showMsg(msg) {
        $.messager.show({
            title: '提示',
            msg: msg,
            showType: 'show'
        });
    }

</script>

CZBK.ItcastOA.WebApp/Views/UserInfo/ShowUserRoleInfo.cshtml
@{
    Layout = null;
}
@using CZBK.ItcastOA.Model
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>为用户分配角色</title>
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
        function subForm() {
            $("#setUserRoleForm").submit();
        }
        function afterSet(data) {
            window.parent.afterSetUserRole(data);
        }
    </script>
</head>
<body>
    <div>
        为  @{
            UserInfo userInfo = ViewBag.UserInfo;
           <span style="font-size:14px;color:red;font-weight:bold"> @userInfo.UName</span>
            
        }  用户分配角色<br />

        @{
            using(Ajax.BeginForm("SetUserRoleInfo","UserInfo",new{},new AjaxOptions(){OnSuccess="afterSet",HttpMethod="post"},new{id="setUserRoleForm"})){
                <input type="hidden" name="userId" value="@userInfo.ID" />
            List<RoleInfo> allRoleList = ViewBag.AllRoleList;
            List<int>roleIdList=ViewBag.AllUserRoleIdList;
            foreach(RoleInfo roleInfo in allRoleList){
                var roleName="cba_"+roleInfo.ID;
                if(roleIdList.Contains(roleInfo.ID))
                {
                   
              <input type="checkbox" name="@roleName" value="@roleInfo.ID" checked="checked" />@roleInfo.RoleName
                    }
                    else
                    {
                 <input type="checkbox" name="@roleName" value="@roleInfo.ID"  />@roleInfo.RoleName
                }
            }
         }
        }

    </div>
</body>
</html>